force-app/main/default/objects/Form_Table__mdt/Form_Table__mdt.object-meta.xml
<CustomObject>
    <description>The form table metadata will hold the information about the form table which will be utilized in the flow or any other form.</description>
    <label>Form Table</label>
    <pluralLabel>Form Tables</pluralLabel>
</CustomObject>

force-app/main/default/objects/Form_Table__mdt/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <description>Group Name is used to use in the related records to fetch all the records related to this form table.</description>
    <inlineHelpText>Enter the form table name.</inlineHelpText>
    <label>Group Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/Form_Table_Element__mdt.object-meta.xml
<CustomObject>
    <label>Form Table Element</label>
    <pluralLabel>Form Table Elements</pluralLabel>
</CustomObject>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Form_Table__c.field-meta.xml
<CustomField>
    <fullName>Form_Table__c</fullName>
    <label>Form Table</label>
    <referenceTo>Form_Table__mdt</referenceTo>
    <relationshipLabel>Form Table Elements</relationshipLabel>
    <relationshipName>Form_Table_Elements</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/TestFormTableController.cls
/**
* @Author Rajkiran Dewara
* @Since 24-06-2019
* @Description: Test class to coverage the FormTableController class.
*/
@isTest
public class TestFormTableController {
	
   /**
    * @Author Rajkiran Dewara
    * @Since 24-06-2019
    * @Description: Test method to verify the metadata record in the
    * metadata table
    */
    
    @isTest
    public static void testComponentsByGroupNameNew(){
        List<Form_Table__mdt> formtablemdt = [Select Group_Name__c From Form_Table__mdt];
        Test.startTest();
        for(Form_Table__mdt ftm:  formtablemdt){
            system.assertNotEquals(ftm, null, 'Data list ');
            List<Form_Table_Element__mdt> formtablelemntmdt = [Select Form_Table__c From Form_Table_Element__mdt where Form_Table__c = :ftm.id];
            system.assertNotEquals(formtablelemntmdt, null, 'Data list ');
            system.assertNotEquals(formtablelemntmdt.size(), 0, 'Data list size ');
            List<RepeaterComponentWrapper> listOfRepeaterDataDynamicdata = FormTableController.getComponentsByGroupNameNew(formtablemdt[0].Group_Name__c);
            system.assertNotEquals(listOfRepeaterDataDynamicdata, null, 'Data list ');
            //system.assertNotEquals(listOfRepeaterDataDynamicdata.size(), 0, 'Data list ');
            if(listOfRepeaterDataDynamicdata != null && listOfRepeaterDataDynamicdata.size()>0){
                for(RepeaterComponentWrapper rcw :listOfRepeaterDataDynamicdata)
                system.assertNotEquals(rcw, null, 'Attributes ');            
            }
        }
        Test.stopTest();
    }
}