force-app/main/default/objects/Form_Table__mdt/Form_Table__mdt.object-meta.xml
<CustomObject>
    <description>The form table metadata will hold the information about the form table which will be utilized in the flow or any other form.</description>
    <label>Form Table</label>
    <pluralLabel>Form Tables</pluralLabel>
</CustomObject>

force-app/main/default/objects/Form_Table__mdt/fields/Column_1__c.field-meta.xml
<CustomField>
    <fullName>Column_1__c</fullName>
    <label>Column 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table__mdt/fields/Column_2__c.field-meta.xml
<CustomField>
    <fullName>Column_2__c</fullName>
    <label>Column 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table__mdt/fields/Column_3__c.field-meta.xml
<CustomField>
    <fullName>Column_3__c</fullName>
    <label>Column 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table__mdt/fields/Column_4__c.field-meta.xml
<CustomField>
    <fullName>Column_4__c</fullName>
    <label>Column 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table__mdt/fields/Column_5__c.field-meta.xml
<CustomField>
    <fullName>Column_5__c</fullName>
    <label>Column 5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table__mdt/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <description>Give the formula as it required to identify in the formula calculation.</description>
    <inlineHelpText>Give the formula as it required to identify in the formula calculation.
make sure it follows the correct formula see in below example.
Ex: column5 + column3 - column4</inlineHelpText>
    <label>Formula</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form_Table__mdt/fields/Formula_Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Formula_Column_Name__c</fullName>
    <description>Give the comma-separated formula column name as it required to identify in the formula calculation.</description>
    <inlineHelpText>Give the comma-separated formula column name as it required to identify in the formula calculation.
make sure it follows the below example name.
Ex: column5,column3,column4</inlineHelpText>
    <label>Formula Column Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table__mdt/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <description>Group Name is used to use in the related records to fetch all the records related to this form table.</description>
    <inlineHelpText>Enter the form table name.</inlineHelpText>
    <label>Group Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/Form_Table_Element__mdt.object-meta.xml
<CustomObject>
    <label>Form Table Element</label>
    <pluralLabel>Form Table Elements</pluralLabel>
</CustomObject>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Name_2_Column_1_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Name_2_Column_1_Component__c</fullName>
    <label>Attribute Name 2 Column 1 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Name_2_Column_2_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Name_2_Column_2_Component__c</fullName>
    <label>Attribute Name 2 Column 2 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Name_2_Column_3_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Name_2_Column_3_Component__c</fullName>
    <label>Attribute Name 2 Column 3 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Name_2_Column_4_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Name_2_Column_4_Component__c</fullName>
    <label>Attribute Name 2 Column 4 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Name_2_Column_5_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Name_2_Column_5_Component__c</fullName>
    <label>Attribute Name 2 Column 5 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Name_3_Column_1_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Name_3_Column_1_Component__c</fullName>
    <label>Attribute Name 3 Column 1 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Name_3_Column_2_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Name_3_Column_2_Component__c</fullName>
    <label>Attribute Name 3 Column 2 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Name_3_Column_3_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Name_3_Column_3_Component__c</fullName>
    <label>Attribute Name 3 Column 3 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Name_3_Column_4_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Name_3_Column_4_Component__c</fullName>
    <label>Attribute Name 3 Column 4 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Name_3_Column_5_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Name_3_Column_5_Component__c</fullName>
    <label>Attribute Name 3 Column 5 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Name_Column_1_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Name_Column_1_Component__c</fullName>
    <label>Attribute Name Column 1 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Name_Column_2_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Name_Column_2_Component__c</fullName>
    <label>Attribute Name Column 2 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Name_Column_3_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Name_Column_3_Component__c</fullName>
    <label>Attribute Name Column 3 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Name_Column_4_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Name_Column_4_Component__c</fullName>
    <label>Attribute Name Column 4 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Name_Column_5_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Name_Column_5_Component__c</fullName>
    <label>Attribute Name Column 5 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Value_2_Column_1_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Value_2_Column_1_Component__c</fullName>
    <label>Attribute Value 2 Column 1 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Value_2_Column_2_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Value_2_Column_2_Component__c</fullName>
    <label>Attribute Value 2 Column 2 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Value_2_Column_3_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Value_2_Column_3_Component__c</fullName>
    <label>Attribute Value 2 Column 3 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Value_2_Column_4_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Value_2_Column_4_Component__c</fullName>
    <label>Attribute Value 2 Column 4 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Value_2_Column_5_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Value_2_Column_5_Component__c</fullName>
    <label>Attribute Value 2 Column 5 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Value_3_Column_1_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Value_3_Column_1_Component__c</fullName>
    <label>Attribute Value 3 Column 1 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Value_3_Column_2_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Value_3_Column_2_Component__c</fullName>
    <label>Attribute Value 3 Column 2 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Value_3_Column_3_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Value_3_Column_3_Component__c</fullName>
    <label>Attribute Value 3 Column 3 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Value_3_Column_4_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Value_3_Column_4_Component__c</fullName>
    <label>Attribute Value 3 Column 4 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Value_3_Column_5_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Value_3_Column_5_Component__c</fullName>
    <label>Attribute Value 3 Column 5 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Value_Column_1_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Value_Column_1_Component__c</fullName>
    <label>Attribute Value Column 1 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Value_Column_2_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Value_Column_2_Component__c</fullName>
    <label>Attribute Value Column 2 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Value_Column_3_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Value_Column_3_Component__c</fullName>
    <label>Attribute Value Column 3 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Value_Column_4_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Value_Column_4_Component__c</fullName>
    <label>Attribute Value Column 4 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Attribute_Value_Column_5_Component__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Value_Column_5_Component__c</fullName>
    <label>Attribute Value Column 5 Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Column_1_Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_1_Component_Name__c</fullName>
    <label>Column 1 Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Column_2_Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_2_Component_Name__c</fullName>
    <label>Column 2 Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Column_3_Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_3_Component_Name__c</fullName>
    <label>Column 3 Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Column_4_Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_4_Component_Name__c</fullName>
    <label>Column 4 Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Column_5_Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_5_Component_Name__c</fullName>
    <label>Column 5 Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Display_Rank__c.field-meta.xml
<CustomField>
    <fullName>Display_Rank__c</fullName>
    <label>Display Rank</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Form_Table_Element__mdt/fields/Form_Table__c.field-meta.xml
<CustomField>
    <fullName>Form_Table__c</fullName>
    <label>Form Table</label>
    <referenceTo>Form_Table__mdt</referenceTo>
    <relationshipLabel>Form Table Elements</relationshipLabel>
    <relationshipName>Form_Table_Elements</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/FormTableController.cls
/**
* @Author Incapsulate
* @Since 08-05-2019
* @Description: The class is used to fetch the details of data grid based on custom metadata defined in the system. 
*/
public class FormTableController {
   /**
    * @Author Incapsulate
    * @Since 08-03-2019
    * @Description: This method is used to fetch the
    */
    @AuraEnabled
    public static List<RepeaterComponentWrapper> getComponentsByGroupNameNew(String groupName) {
        
        List<RepeaterComponentWrapper> wrappedComponents = new List<RepeaterComponentWrapper>();
            for (Form_Table_Element__mdt cmp : [SELECT Id, DeveloperName,Form_Table__r.Group_Name__c,
                                                                   Form_Table__r.Column_1__c,
                                                                   Form_Table__r.Column_2__c,
                                                                   Form_Table__r.Column_3__c,
                                                                   Form_Table__r.Column_4__c,
                                                                   Form_Table__r.Column_5__c,
                                                                   Form_Table__r.Formula_Column_Name__c,
                                                                   Form_Table__r.Formula__c,
                                                                   
                                                                   Column_1_Component_Name__c, Column_2_Component_Name__c, 
                                                                   Column_3_Component_Name__c, Column_4_Component_Name__c, 
                                                                   Column_5_Component_Name__c, 
                                                                   
                                                                   Attribute_Name_Column_1_Component__c, Attribute_Name_Column_2_Component__c, 
                                                                   Attribute_Name_Column_3_Component__c, Attribute_Name_Column_4_Component__c, 
                                                                   Attribute_Name_Column_5_Component__c, 
                                                                   Attribute_Name_2_Column_1_Component__c, Attribute_Name_2_Column_2_Component__c, 
                                                                   Attribute_Name_2_Column_3_Component__c, Attribute_Name_2_Column_4_Component__c, 
                                                                   Attribute_Name_2_Column_5_Component__c, 
                                                                   Attribute_Name_3_Column_1_Component__c, Attribute_Name_3_Column_2_Component__c, 
                                                                   Attribute_Name_3_Column_3_Component__c, Attribute_Name_3_Column_4_Component__c, 
                                                                   Attribute_Name_3_Column_5_Component__c, 
                                                                
                                                                   Attribute_Value_Column_1_Component__c,Attribute_Value_Column_2_Component__c, 
                                                                   Attribute_Value_Column_3_Component__c,Attribute_Value_Column_4_Component__c, 
                                                                   Attribute_Value_Column_5_Component__c,
                                                                   Attribute_Value_2_Column_1_Component__c,Attribute_Value_2_Column_2_Component__c, 
                                                                   Attribute_Value_2_Column_3_Component__c,Attribute_Value_2_Column_4_Component__c, 
                                                                   Attribute_Value_2_Column_5_Component__c,
                                                                   Attribute_Value_3_Column_1_Component__c,Attribute_Value_3_Column_2_Component__c, 
                                                                   Attribute_Value_3_Column_3_Component__c,Attribute_Value_3_Column_4_Component__c, 
                                                                   Attribute_Value_3_Column_5_Component__c,
                                                      
                                                                   Display_Rank__c, Form_Table__c FROM Form_Table_Element__mdt where
                                                                   Form_Table__r.Group_Name__c = :groupName order by Display_Rank__c asc])
            {
                Map<String, Object> attributes = new Map<String, Object>();
                Map<String,String> attributeNameValue = new Map<String,String>();
                attributeNameValue.put(cmp.Attribute_Name_Column_1_Component__c,cmp.Attribute_Value_Column_1_Component__c);
                attributeNameValue.put(cmp.Attribute_Name_2_Column_1_Component__c,cmp.Attribute_Value_2_Column_1_Component__c);
                attributeNameValue.put(cmp.Attribute_Name_3_Column_1_Component__c,cmp.Attribute_Value_3_Column_1_Component__c);
                 prepareAttribute(attributes,attributeNameValue, cmp.Column_1_Component_Name__c,wrappedComponents,cmp);
                
                attributes = new Map<String, Object>();                
                attributeNameValue = new Map<String,String>();
                attributeNameValue.put(cmp.Attribute_Name_Column_2_Component__c,cmp.Attribute_Value_Column_2_Component__c);
                attributeNameValue.put(cmp.Attribute_Name_2_Column_2_Component__c,cmp.Attribute_Value_2_Column_2_Component__c);
                attributeNameValue.put(cmp.Attribute_Name_3_Column_2_Component__c,cmp.Attribute_Value_3_Column_2_Component__c);
                 prepareAttribute(attributes,attributeNameValue, cmp.Column_2_Component_Name__c,wrappedComponents,cmp);
                
                attributes = new Map<String, Object>();
                attributeNameValue = new Map<String,String>();
                attributeNameValue.put(cmp.Attribute_Name_Column_3_Component__c,cmp.Attribute_Value_Column_3_Component__c);
                attributeNameValue.put(cmp.Attribute_Name_2_Column_3_Component__c,cmp.Attribute_Value_2_Column_3_Component__c);
                attributeNameValue.put(cmp.Attribute_Name_3_Column_3_Component__c,cmp.Attribute_Value_3_Column_3_Component__c);
                 prepareAttribute(attributes,attributeNameValue, cmp.Column_3_Component_Name__c,wrappedComponents,cmp);
                
                attributes = new Map<String, Object>();
                attributeNameValue = new Map<String,String>();
                attributeNameValue.put(cmp.Attribute_Name_Column_4_Component__c,cmp.Attribute_Value_Column_4_Component__c);
                attributeNameValue.put(cmp.Attribute_Name_2_Column_4_Component__c,cmp.Attribute_Value_2_Column_4_Component__c);
                attributeNameValue.put(cmp.Attribute_Name_3_Column_4_Component__c,cmp.Attribute_Value_3_Column_4_Component__c);
                 prepareAttribute(attributes,attributeNameValue, cmp.Column_4_Component_Name__c,wrappedComponents,cmp);
                
                attributes = new Map<String, Object>();
                attributeNameValue = new Map<String,String>();
                attributeNameValue.put(cmp.Attribute_Name_Column_5_Component__c,cmp.Attribute_Value_Column_5_Component__c);
                attributeNameValue.put(cmp.Attribute_Name_2_Column_5_Component__c,cmp.Attribute_Value_2_Column_5_Component__c);
                attributeNameValue.put(cmp.Attribute_Name_3_Column_5_Component__c,cmp.Attribute_Value_3_Column_5_Component__c);
                prepareAttribute(attributes,attributeNameValue, cmp.Column_5_Component_Name__c,wrappedComponents,cmp);                
                
            }                           
        return wrappedComponents;
    }
    
     /**
    * @Author Incapsulate
    * @Since 08-03-2019
    * @Description: 
    */
    private static void prepareAttribute(Map<String, Object> attributes,Map<String,String> attributeNameValue,String cmpName,List<RepeaterComponentWrapper> wrappedComponents,Form_Table_Element__mdt cmp){
        for(String key : attributeNameValue.keySet()){
            if(String.isNotEmpty(key)){
                putAttribute(attributes, key, 'String', attributeNameValue.get(key));  
            }           
        }
        prepareElement(attributes,cmpName,wrappedComponents,cmp);
    }
    
     /**
    * @Author Incapsulate
    * @Since 08-03-2019
    * @Description: 
    */
    private static List<RepeaterComponentWrapper> prepareElement(Map<String, Object> attributes,String cmpName,List<RepeaterComponentWrapper> wrappedComponents,Form_Table_Element__mdt cmp){                                 
                    RepeaterComponentWrapper.RepeaterCard rc = new RepeaterComponentWrapper.RepeaterCard();
                    rc.name = cmpName;
                    rc.metadataRecordDeveloperName = cmp.DeveloperName;
                    //for form table header
                    rc.listOfColumn = new List<String>();
                    rc.column1 = cmp.Form_Table__r.Column_1__c;
                    rc.column2 = cmp.Form_Table__r.Column_2__c;
                    rc.column3 = cmp.Form_Table__r.Column_3__c;
                    rc.column4 = cmp.Form_Table__r.Column_4__c;
                    rc.column5 = cmp.Form_Table__r.Column_5__c;
                    rc.formulaColumnName = cmp.Form_Table__r.Formula_Column_Name__c;
                    rc.formula = cmp.Form_Table__r.Formula__c;
                    rc.listOfColumn.add(cmp.Form_Table__r.Column_1__c);
                    rc.listOfColumn.add(cmp.Form_Table__r.Column_2__c);
                    rc.listOfColumn.add(cmp.Form_Table__r.Column_3__c);
                    rc.listOfColumn.add(cmp.Form_Table__r.Column_4__c);
                    rc.listOfColumn.add(cmp.Form_Table__r.Column_5__c);
                    RepeaterComponentWrapper rcw = new RepeaterComponentWrapper();
                    //element prepared with attribute infomation end here
                    rcw.sections.add(new RepeaterComponentWrapper(rc, attributes));               
                    wrappedComponents.add(rcw);
            return wrappedComponents;        
    }
   
     /**
    * @Author Incapsulate
    * @Since 08-03-2019
    * @Description: 
    */
    private static void putAttribute(Map<String, Object> attributes, String attrName, String attrType, String attrValue) {
        if(String.isNotBlank(attrName)) {
            Object value = null;
            try{
                switch on attrType {
                    when 'Number' { value = JSON.deserializeUntyped(attrValue); }
                    when 'Checkbox' { value = JSON.deserializeUntyped(attrValue); }
                    when 'JSON' { value = JSON.deserializeUntyped(attrValue); }
                    when else { value = attrValue; }
                }
            }
            catch(Exception ex) {
                System.debug('Unable to get value for attribute: ' + attrName);
            }
            attributes.put(attrName, value);
        }
    }

}